### ISSUE TITLE
StyleCI Broken

### ISSUE THREAD

**Issue by GrahamCampbell** [SIJOT/SIJOT-2.x#62]
The user the enabled StyleCI is no longer an admin on GitHub, so StyleCI is broken.

**Comment by GrahamCampbell** [comment]
Or, at least something's broken. GitHub's returning 404s at our end, indicating lacking permission.

**Comment by Tjoosten** [comment]
Can u explain more plz

**Comment by GrahamCampbell** [comment]
I was hoping you'd know what you'd changed. GitHub is returning a 404 for us.

**Comment by Tjoosten** [comment]
Danm
